### PR TITLE
calls ishookactive via reflection instead of directly

### PR DESCRIPTION
**Pull request by 4d616e61**
The issue that I had with adofaitweaks was that getting isHookActive via the getter directly wasn't working properly, so this fix manually finds said getter and calls it, which fixes the issue for me
I don't know if this is the issue(getter not properly being called) that everyone is having but hopefully it fixes the issue on everyone's end. As such I think it would be good to test it out first or something idk

### CODE REVIEW

**Comment by 4d616e61** [comment]
goes without saying that keylimiter works(at least for me) btw

**Comment by PizzaLovers007** [comment]
Hey, thanks for the PR! Like I mentioned in #28, I'm not at my usual setup and thus actually can't make builds for the mod. Reflection is probably the way to go, but I want to verify that both current and older versions work before releasing an update. I'll review this more thoroughly when I can!

**Comment by 4d616e61** [comment]
Thanks for the response! If you feel comfortable running binaries, here is my build:
https://cdn.discordapp.com/attachments/1025949316621279296/1179749544079130695/AdofaiTweaks-2.6.5.zip?ex=657aea61&is=65687561&hm=973b0c62951335d8dba2eab030e19e800c32cdaf10ee7322576c629ea1301781&

**Comment by PizzaLovers007** [comment]
I made some changes to make sure this PR is backwards compatible. Reflection is definitely the way to go here, so thanks for the initial fix!

**Pull request merged**
